{% raw -%}
---
- block:
  - name: "Query kernel-devel packages."
    command: rpm -q --qf='%{VERSION}-%{RELEASE}.%{ARCH}\n' kernel-devel
    changed_when: False
    register: rpm_query

  - name: "Verify kernel-devel version."
    assert:
      that: ansible_kernel in rpm_query.stdout_lines
      success_msg: "kernel-devel-{{ ansible_kernel }} is installed."
      fail_msg: "kernel-devel-{{ ansible_kernel }} is not installed. Will attempt to install."

  rescue:
  - block:
    - name: "Install kernel-devel package."
      become: yes
      yum:
        state: present
        name: "kernel-devel-uname-r == {{ ansible_kernel }}"

    rescue:
    - fail:
        msg: >
          Refusing to update kernel and reboot.  Manually update your kernel or
          set 'driver.prepare.allow_reboot' to 'yes' and retry.
      when: not allow_reboot

    - name: "Update kernel."
      become: yes
      block:
      - name: "Update kernel."
        yum:
          state: latest
          name:
          - kernel
          - kernel-devel
        register: yum_update_results

      - name: "Reboot."
        when: yum_update_results.changed
        reboot:
          reboot_timeout: 600

      - name: "Wait for reboot to finish."
        when: yum_update_results.changed
        wait_for_connection:

      - name: "Regather facts after reboot."
        when: yum_update_results.changed
        setup:
{% endraw -%}
