---
dependency:
  name: galaxy
  enabled: yes
  requirements-file: collections.yml

driver:
{%- if cookiecutter.driver == 'unmanaged' %}
  name: delegated
  options:
    # Note: You must configure ~/.ssh/config
    managed: False
    login_cmd_template: 'ssh {instance}'
    ansible_connection_options:
      ansible_connection: ssh
      ansible_ssh_common_args: ''
{%- elif cookiecutter.driver == 'vagrant/virtualbox' %}
  name: vagrant
  provider:
    name: virtualbox
{%- elif cookiecutter.driver == 'vagrant/libvirt' %}
  name: vagrant
  provider:
    name: libvirt
{%- elif cookiecutter.driver == 'vagrant/vmware_desktop' %}
  name: vagrant
  provider:
    name: vmware_desktop
{%- elif cookiecutter.driver == 'proxmox' %}
  name: proxmox
  options:
    #api_host: <hostname>
    #api_user: <user>@pam
    #api_password: <password>
    #node: <node>
    #ssh_user: <ssh-username>
    #ssh_identity_file: <ssh-keyname>
    timeout: 300
{%- endif %}
  prepare:
    bootstrap_python: yes
    allow_reboot: yes
    selinux_mode: permissive
    rewrite_hosts_file: yes

platforms:
  - name: "{{ cookiecutter.instance }}"
{%- if cookiecutter.driver.startswith('vagrant') %}
    box: "{{ cookiecutter.image_name }}"
{%- elif cookiecutter.driver == 'proxmox' %}
    proxmox_template_name: "{{ cookiecutter.image_name }}"
{%- endif %}
    groups:
      - afs_admin_client
      - afs_clients
      - afs_databases
      - afs_fileservers
      - afs_kdcs
      - afs_test
{%- if cookiecutter.install_method in ('packages', 'bdist', 'sdist') %}
      - afs_builders
{%- endif %}

provisioner:
  name: ansible
  playbooks:
    prepare: "${MOLECULE_SCENARIO_DIRECTORY}/../playbooks/prepare.yml"
    converge: "${MOLECULE_SCENARIO_DIRECTORY}/../playbooks/converge.yml"
    cleanup: "${MOLECULE_SCENARIO_DIRECTORY}/../playbooks/cleanup.yml"
  inventory:
    group_vars:
      all:
        afs_realm: "{{ cookiecutter.realm }}"
        afs_cell: "{{ cookiecutter.cell }}"
        afs_user: "{{ cookiecutter.user }}"
        afs_admin: "{{ cookiecutter.admin }}"
        afs_security_model: "none"

        afs_realm_files: "${MOLECULE_EPHEMERAL_DIRECTORY}"
        afs_cell_files: "${MOLECULE_EPHEMERAL_DIRECTORY}"
        afs_csdb_file: "${MOLECULE_EPHEMERAL_DIRECTORY}/csdb.yaml"

        afs_install_method: "{{ cookiecutter.install_method }}"
{%- if cookiecutter.install_method == 'managed' %}
        # managed options
  {%- if cookiecutter.enable_dkms == 'yes' %}
        afs_module_install_method: "dkms"
  {%- else %}
        afs_module_install_method: "kmod"
  {%- endif %}
{%- elif cookiecutter.install_method == 'packages' %}
        # packages options
        afs_install_archive: "${MOLECULE_PROJECT_DIRECTORY}/builds/${MOLECULE_SCENARIO_NAME}.tar.gz"
  {%- if cookiecutter.enable_dkms == 'yes' %}
        afs_module_install_method: "dkms"
  {%- else %}
        afs_module_install_method: "kmod"
  {%- endif %}
{%- elif cookiecutter.install_method == 'bdist' %}
        # bdist options
        afs_install_archive: "${MOLECULE_PROJECT_DIRECTORY}/builds/${MOLECULE_SCENARIO_NAME}.tar.gz"
{%- elif cookiecutter.install_method == 'sdist' %}
        # sdist options
        afs_install_archive: "${MOLECULE_PROJECT_DIRECTORY}/builds/${MOLECULE_SCENARIO_NAME}.tar.gz"
{%- elif cookiecutter.install_method == 'source' %}
        # source options
{%- endif %}

{%- if cookiecutter.install_method in ('packages', 'bdist', 'sdist') %}
      afs_builders:
        afs_git_repo: "${AFS_GIT_REPO:-git://git.openafs.org/openafs}"
        afs_git_version: "${AFS_GIT_VERSION:-master}"
        afs_configure_options:
          enable:
            - transarc-paths
            - debug
            - debug-kernel
            - kernel-module
          disable:
            - optimize
          with:
            - linux-kernel-packaging
{%- endif %}

      afs_test:
        afs_robotest_fileserver_a: "{{ cookiecutter.instance }}"

verifier:
  name: robotframework
  enabled: true
  group: afs_test
  libraries:
    - robotframework-openafslibrary
  test_repos:
    - name: openafs-robotest
      repo: https://github.com/openafs-contrib/openafs-robotest
      version: master
  resources:
    - ${MOLECULE_SCENARIO_DIRECTORY}/../templates/openafs-robotest.yml.j2
  data_sources:
    - openafs-robotest/tests
  dest_dir: ${MOLECULE_PROJECT_DIRECTORY}/reports/${MOLECULE_SCENARIO_NAME}
  options:
    exclude:
      - bug
      - slow
      - rogue-avoidance
      - requires-multi-fs
    loglevel: INFO
    debugfile: debug.log
    runemptysuite: true
    variablefile: openafs-robotest.yml

scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
