---
- import_playbook: prepare_instances.yml

{%- if cookiecutter.build_packages == 'yes' %}
  {%- if cookiecutter.install_method == 'packages' %}
    {%- if cookiecutter.platform in ['alma8', 'fedora36'] %}
- import_playbook: build/rhel.yml
    {%- elif cookiecutter.platform in ['debian11'] %}
- import_playbook: build/debs.yml
    {%- endif %}
  {%- elif cookiecutter.install_method == 'bdist' %}
- import_playbook: build/bdist.yml
  {%- elif cookiecutter.install_method == 'sdist' %}
- import_playbook: build/sdist.yml
  {%- endif %}
{%- endif %}
